name: Pipeline

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: notesync

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          # Change a folder because a Python module name can't have dashes
          path: notesync

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgl1-mesa-dev
          version: 1.0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "notesync/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.21"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uvx flake8 . --count --show-source --statistics

      - name: Test with pytest
        run: |
          uv run pytest

      - name: Create ankiaddon
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          zip -r notesync-${{ github.ref_name }}.ankiaddon * --exclude '__pycache__/*' --exclude meta.json

      - name: Create a release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./notesync/notesync-${{ github.ref_name }}.ankiaddon
